---
vaults:
  - name: ssh-vault
    template: fedora-32
    label: black
    mem: 400
    vcpus: 2
    autostart: True

clients:
  - name: ssh-client
    template: fedora-32
    label: blue
    mem: 400
    vcpus: 2
    autostart: False

